### ISSUE TITLE
Risk of Rain 2 | Can't exit drop pod

### ISSUE THREAD

**Issue by wither932** [harbingerofme/Bepinex.Monomod.HookGenPatcher#10]
When installed on Risk of Rain 2 it does not allow players to exit the Drop pod upon starting. I have not tried with Mul-t or Acrid yet but every survivor I have tried so far who have a drop pod seem to be unable to exit the drop pod. Main visual imagery of issue is that the "Press E to exit drop pod" text is not there and pressing E does not allow exiting the pod. I have tried running with just Bepinex and HookGenPatcher and the issue is seen with only HookGenPatcher. Issue is also seen with controller.

**Comment by harbingerofme** [comment]
If the issue is seen without bepinex but hookgenpatcher, then your pc is haunted as hookgenpatcher can't run without bepinex

**Comment by wither932** [comment]
May wanna reread my issue because I meant I only had bepinex and hookgenpatcher installed and the issue occured

**Comment by harbingerofme** [comment]
You may want to consider this is a general bepinex unity patcher. Risk of Rain 2 has their own separate distributions for bepinex and hookgen. Please raise issues in the risk of rain 2 modding discord

**Comment by wither932** [comment]
Ok. Ill try that soon.
