### ISSUE TITLE
bbepis-BepInExPack-5.4.1801 not available any longer

### ISSUE THREAD

**Issue by CelesteGH** [harbingerofme/Bepinex.Monomod.HookGenPatcher#16]
I get this error : 
Error
bbepis-BepInExPack-5.4.1801 could not be found
You may be offline, or the mod was removed from Thunderstore.

Suggestion
The dependency may not yet be published to Thunderstore and may be available elsewhere.

**Comment by harbingerofme** [comment]
Use any newer version of BepInEx 5.4 instead.

**Comment by CelesteGH** [comment]
I have but it still states that there is a missing dependency in r2modman

**Comment by harbingerofme** [comment]
Sounds like an issue for r2modman instead.
