### ISSUE TITLE
Failed to run Initializer of BepInEx.MonoMod.HookGenPatcher.HookGenPatcher

### ISSUE THREAD

**Issue by MetaControl** [harbingerofme/Bepinex.Monomod.HookGenPatcher#4]
I am getting an errors at initialization:

```
[Error  :   BepInEx] Failed to run Initializer of BepInEx.MonoMod.HookGenPatcher.HookGenPatcher: System.IO.FileNotFoundException: Could not find file 'E:\SteamLibrary\steamapps\common\Valheim\valheim_Data\Managed\Assembly-CSharp.dll'.
File name: 'E:\SteamLibrary\steamapps\common\Valheim\valheim_Data\Managed\Assembly-CSharp.dll'
  at System.IO.__Error.WinIOError (System.Int32 errorCode, System.String maybeFullPath) [0x000c4] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at System.IO.FileInfo.get_Length () [0x0003f] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at BepInEx.MonoMod.HookGenPatcher.HookGenPatcher.Initialize () [0x000cd] in <317afaf7b64144569b3ecdf9c8174f64>:0 
  at BepInEx.Preloader.Patching.AssemblyPatcher.InitializePatchers () [0x0001e] in <2117efc3e8e64db7876a6381857f86e1>:0 
```

```
[Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'MMHOOK_assembly_valheim, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
ValheimLib.ValheimLib.Awake () (at <5f36a1563d4442b8a841887b90fe36e9>:0)
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
```

**Comment by harbingerofme** [comment]
Hello, this might be an issue with Valheim's specific setup. Perhaps their modding discord can help you out better than me: [https://discord.gg/RBq2mzeu4z](https://discord.gg/RBq2mzeu4z)

**Comment by xiaoxiao921** [comment]
Hi,
Did you manually install the hookgen patcher ? the hookgen patcher for valheim ship with a config folder inside the .zip
That config file is necessary for hookgen to work properly. Make sure that the config file in `BepInEx\config\HookGenPatcher.cfg` is present
If you installed it through a mod manager, could you tell me which one you used ?

**Comment by MetaControl** [comment]
> Hi,
> Did you manually install the hookgen patcher ? 

yes, i installed it manually. with all the files in their place.

**Comment by xiaoxiao921** [comment]
> > Hi,
> > Did you manually install the hookgen patcher ?
> 
> yes, i installed it manually. with all the files in their place.

I suspect that you forgot the .cfg file the first time, and now since you launched the game once, the cfg file got generated with default values

**Comment by MetaControl** [comment]
> I suspect that you forgot the .cfg file the first time, and now since you launched the game once, the cfg file got generated with default values
i was sure that i copied it... mhhh... never mind. i tried it again, double checked for the config, and it works now. thanks.
