### ISSUE TITLE
HookGenPatcher "set_scene" is not a recognized ConCommand or ConVar error

### ISSUE THREAD

**Issue by Weed-Seagull** [harbingerofme/Bepinex.Monomod.HookGenPatcher#7]
I am using HookGenPatcher with BepInExPack using r2modman for Risk of Rain 2, Whenever I try to launch the game, it gets past the hopoo games splash screen and then gets stuck on a black screen. I am using the latest versions of both mods.

**Comment by harbingerofme** [comment]
Can you provide a log file?

> A full log is way more useful for finding what your mod problem is.
If you are using r2modman or Thunderstore Mod Manager:
You can copy your log by going to the Settings screen, selecting the Debugging tab and clicking Copy LogOutput.log to clipboard. Then paste it here.
If you have manual install:
You can find such log file in your Risk of Rain 2/BepInEx/ folder, the file is called LogOutput.log.

**Comment by Weed-Seagull** [comment]
﻿```[Message:   BepInEx] BepInEx 5.4.9.0 - Risk of Rain 2
[Info   :   BepInEx] Running under Unity v2018.4.16.15133130
[Info   :   BepInEx] CLR runtime version: 4.0.30319.17020
[Info   :   BepInEx] Supports SRE: False
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.MonoMod.Loader 1.0.0.0]
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.MonoMod.HookGenPatcher 1.1.0.0]
[Info   :   BepInEx] 3 patcher plugins loaded
[Info   :HookGenPatcher] Previous MMHOOK location found. Using that location to save instead.
[Info   :HookGenPatcher] Already ran for this version, reusing that file.
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Info   :   MonoMod] Collecting target assemblies from mods
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 1 plugins to load
[Info   :   BepInEx] Loading [R2API 3.0.44]
[Error  : Unity Log] TypeLoadException: Could not resolve type with token 01000106 (from typeref, class/assembly RoR2.ContentManagement.IContentPackProvider, Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
Stack trace:
UnityEngine.GameObject:AddComponent(Type)
BepInEx.Bootstrap.Chainloader:Start()
UnityEngine.Application:.cctor()
RoR2.Console:RegisterLogHandler()

[Message:   BepInEx] Chainloader startup complete
[Info   :   Console] Facepunch.Steamworks Unity: WindowsPlayer
[Info   : Unity Log] Facepunch.Steamworks Unity: WindowsPlayer

[Info   :   Console] Facepunch.Steamworks Os: Windows
[Info   : Unity Log] Facepunch.Steamworks Os: Windows

[Info   :   Console] Facepunch.Steamworks Arch: x64
[Info   : Unity Log] Facepunch.Steamworks Arch: x64

[Info   :   Console] Searching for compatible XInput library...
[Info   : Unity Log] Searching for compatible XInput library...

[Info   :   Console] Found Xinput1_4.dll.
[Info   : Unity Log] Found Xinput1_4.dll.

[Info   : Unity Log] Initializing Mod System...
[Info   : Unity Log] Mod System initialized.
[Info   : Unity Log] WwiseUnity: Sound engine initialized successfully.
[Info   : Unity Log] Setting current language to "en"
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
RoR2.Console.Awake () (at <c36b0eadbe0a4afc83f7e70a917dc2c1>:0)
UnityEngine.GameObject:AddComponent()
RoR2.RoR2Application:OnLoad()
RoR2.RoR2Application:Awake()

[Error  : Unity Log] Skin skinCrocoDefault (RoR2.SkinDef) has an empty renderer field in its rendererInfos.
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
RoR2.SystemInitializerAttribute.Execute () (at <c36b0eadbe0a4afc83f7e70a917dc2c1>:0)
RoR2.RoR2Application.OnLoad () (at <c36b0eadbe0a4afc83f7e70a917dc2c1>:0)
RoR2.RoR2Application.Awake () (at <c36b0eadbe0a4afc83f7e70a917dc2c1>:0)

[Info   : Unity Log] Active scene changed from  to splash
[Info   : Unity Log] Loaded scene splash loadSceneMode=2
[Info   : Unity Log] "set_scene" is not a recognized ConCommand or ConVar.
```
Here is my entire log file. It never got past the `[Info   : Unity Log] "set_scene" is not a recognized ConCommand or ConVar.` line

**Comment by harbingerofme** [comment]
Seems like an upstream (or rather offstream) [r2api](https://github.com/risk-of-thunder/R2API/issues) issue.

I've linked this issue in the `#tech-support` channel of the RoR2 modding discord.

This most often happens when running nonsteam versions of the game, such as pirated versions.
