### ISSUE TITLE
InputText moved to Terminal base class

### ISSUE THREAD

**Issue by Geethebluesky** [harbingerofme/Bepinex.Monomod.HookGenPatcher#8]
Getting this warning when HookGen loads. 

The InputText moved, this broke a few other mods who had to move InputText after Hearth & Home updated, so I'm assuming it should be updated in here too.

[Warning:  HarmonyX] AccessTools.DeclaredMethod: Could not find method for type Console and name InputText and parameters
[Warning:  HarmonyX] Unknown patch - Could not find method InputText with 0 parameters in type Console, but it was found in base class of this type Terminal

**Comment by harbingerofme** [comment]
Hookgenpatcher is not aware of any game in the first place. It is a general bepinex patcher.

**Comment by harbingerofme** [comment]
Spoke to to valheim modders, they said this was fixed two days ago: https://github.com/Valheim-Modding/Valheim.DisplayBepInExInfo/commit/9e52defad93f7e02b36dd2fb4a852a97cb6504b8
